### ISSUE TITLE
Missing layout location #extension declaration in shaders

### ISSUE THREAD

**Issue by robbert-vdh** [hecrj/glow_glyph#6]
Right now this (and by extend the master branch iced with the `glow` backend) won't work with OpenGL 3.2 because the the `GL_ARB_explicit_attrib_location` extension has not been explicitly enabled in the GLSL shaders. This is important because OpenGL 3.2 was the last version of OpenGL still supported on macOS, and wgpu sadly still causes too many [segfaults](https://github.com/gfx-rs/wgpu/issues/318) to be usable. This is the error you get when trying to use `glow_glyph` with OpenGL core profile 3.2:

```
0(4) : error C7548: 'layout(location)' requires "#extension GL_ARB_explicit_attrib_location : enable" before use
0(4) : error C0000: ... or #extension GL_ARB_separate_shader_objects : enable
0(4) : error C0000: ... or #version 330
0(5) : error C7548: 'layout(location)' requires "#extension GL_ARB_explicit_attrib_location : enable" before use
0(5) : error C0000: ... or #extension GL_ARB_separate_shader_objects : enable
0(5) : error C0000: ... or #version 330
0(6) : error C7548: 'layout(location)' requires "#extension GL_ARB_explicit_attrib_location : enable" before use
0(6) : error C0000: ... or #extension GL_ARB_separate_shader_objects : enable
0(6) : error C0000: ... or #version 330
0(7) : error C7548: 'layout(location)' requires "#extension GL_ARB_explicit_attrib_location : enable" before use
0(7) : error C0000: ... or #extension GL_ARB_separate_shader_objects : enable
0(7) : error C0000: ... or #version 330
0(8) : error C7548: 'layout(location)' requires "#extension GL_ARB_explicit_attrib_location : enable" before use
0(8) : error C0000: ... or #extension GL_ARB_separate_shader_objects : enable
0(8) : error C0000: ... or #version 330
```

**Comment by hecrj** [comment]
Fixed by #7.
